name: Scott Large
description: 

url: http://www.scottlarge.com/

paginate: 5
paginate_path: _site/notebook/page:num
markdown: redcarpet
permalink: /notebook/:title
pygments: true
analytics :
  provider : google 
  google : 
      tracking_id : 'UA-35809801-1'

