name: Scott Large
description: 

baseurl: http://slarge.github.com/notebook/notebook

paginate: 5
paginate_path: _site/notebook/page:num
markdown: redcarpet
permalink: /notebook/:title
pygments: true
safe: true		
analytics :
  provider : google 
  google : 
      tracking_id : 'UA-35809801-1'

