name: Scott Large
description: 

url: "http://slarge.github.com/notebook"

paginate: 5
paginate_path: _site/notebook/page:num
markdown: redcarpet
permalink: /notebook/:title
pygments: true
analytics :
  provider : google 
  google : 
      tracking_id : 'UA-35809801-1'

